export const parksData = [
  // === กำแพงเพชร / ตาก ===
  { name: "อุทยานแห่งชาติคลองลาน", nameEn: "Khlong Lan National Park", description: "อุทยานแห่งชาติคลองลาน ตั้งอยู่ในจังหวัดกำแพงเพชร มีน้ำตกคลองลานขนาดใหญ่สูงกว่า 100 เมตร เป็นน้ำตกที่สวยงามที่สุดแห่งหนึ่งของภาคเหนือ พื้นที่เป็นป่าดิบชื้นที่อุดมสมบูรณ์", province: "กำแพงเพชร", district: "คลองลาน", latitude: 16.1128, longitude: 99.2544, elevation: 1439, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ชมน้ำตก", "เดินป่า", "แคมป์ปิ้ง"] },
  { name: "อุทยานแห่งชาติคลองวังเจ้า", nameEn: "Khlong Wang Chao National Park", description: "อุทยานแห่งชาติคลองวังเจ้า ครอบคลุมพื้นที่จังหวัดกำแพงเพชรและตาก มีน้ำตกหลายแห่ง ป่าเบญจพรรณ และสัตว์ป่าหลากหลายชนิด เส้นทางเดินป่าผ่านป่าดิบเขาที่สวยงาม", province: "กำแพงเพชร", district: "คลองลาน", latitude: 16.0833, longitude: 99.1500, elevation: 800, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["เดินป่า", "ชมน้ำตก", "ดูสัตว์ป่า"] },
  { name: "อุทยานแห่งชาติแม่วงก์", nameEn: "Mae Wong National Park", description: "อุทยานแห่งชาติแม่วงก์ เชื่อมต่อผืนป่ามรดกโลกทุ่งใหญ่-ห้วยขาแข้ง มีน้ำตกแม่กระสาสวยงาม และเป็นแหล่งอนุรักษ์เสือโคร่งที่สำคัญของประเทศไทย", province: "กำแพงเพชร", district: "แม่วงก์", latitude: 15.9167, longitude: 99.2333, elevation: 1440, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["เดินป่า", "ชมน้ำตก", "ดูสัตว์ป่า", "แคมป์ปิ้ง"] },
  { name: "อุทยานแห่งชาติลานสาง", nameEn: "Lan Sang National Park", description: "อุทยานแห่งชาติลานสาง จังหวัดตาก มีน้ำตกลานสางสวยงาม ผืนป่าเบญจพรรณและป่าดิบแล้ง เหมาะสำหรับเดินป่าระยะสั้นและพักผ่อนหย่อนใจ", province: "ตาก", district: "เมืองตาก", latitude: 16.8500, longitude: 99.0167, elevation: 600, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ชมน้ำตก", "เดินป่า", "แคมป์ปิ้ง"] },
  { name: "อุทยานแห่งชาติน้ำตกพาเจริญ", nameEn: "Namtok Pha Charoen National Park", description: "อุทยานแห่งชาติน้ำตกพาเจริญ จังหวัดตาก มีน้ำตกพาเจริญที่ไหลลดหลั่น 97 ชั้น เป็นน้ำตกหินปูนที่สวยงามในหุบเขาป่าดิบเขา", province: "ตาก", district: "พบพระ", latitude: 16.4833, longitude: 98.7667, elevation: 700, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ชมน้ำตก", "เดินป่า", "ถ่ายภาพ"] },
  { name: "อุทยานแห่งชาติตากสินมหาราช", nameEn: "Taksin Maharat National Park", description: "อุทยานแห่งชาติตากสินมหาราช จังหวัดตาก มีน้ำตกที่สวยงามหลายแห่ง ป่าสนเขตร้อน และจุดชมวิวทะเลหมอกบนยอดเขา เส้นทางธรรมชาติร่มรื่น", province: "ตาก", district: "เมืองตาก", latitude: 16.8833, longitude: 98.8167, elevation: 1123, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ชมน้ำตก", "ชมวิว", "เดินป่า"] },
  { name: "อุทยานแห่งชาติดอยสอยมาลัย-ไม้กลายเป็นหิน", nameEn: "Doi Soi Malai National Park", description: "อุทยานแห่งชาติดอยสอยมาลัย มีแหล่งซากดึกดำบรรพ์ไม้กลายเป็นหินที่ใหญ่ที่สุดในเอเชียตะวันออกเฉียงใต้ ตั้งอยู่ในจังหวัดตาก มีทั้งคุณค่าทางธรณีวิทยาและทางธรรมชาติ", province: "ตาก", district: "บ้านตาก", latitude: 17.0833, longitude: 99.0833, elevation: 500, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ธรณีวิทยา", "เดินป่า", "ถ่ายภาพ"] },
  { name: "อุทยานแห่งชาติแม่เมย", nameEn: "Mae Moei National Park", description: "อุทยานแห่งชาติแม่เมย ตั้งอยู่ริมแม่น้ำเมยชายแดนไทย-เมียนมา จังหวัดตาก มีป่าดิบเขาอุดมสมบูรณ์ สัตว์ป่าหลากหลาย และทิวทัศน์ริมน้ำที่สวยงาม", province: "ตาก", district: "ท่าสองยาง", latitude: 17.2333, longitude: 98.2167, elevation: 600, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["เดินป่า", "ล่องแก่ง", "ดูสัตว์ป่า"] },

  // === เชียงใหม่ ===
  { name: "อุทยานแห่งชาติดอยอินทนนท์", nameEn: "Doi Inthanon National Park", description: "อุทยานแห่งชาติดอยอินทนนท์เป็นที่ตั้งของยอดดอยอินทนนท์ จุดที่สูงที่สุดในประเทศไทย (2,565 เมตร) ตั้งอยู่ในอำเภอจอมทอง จังหวัดเชียงใหม่ มีความสมบูรณ์ของผืนป่า น้ำตกหลายแห่ง และเป็นแหล่งดูนกที่สำคัญ", province: "เชียงใหม่", district: "จอมทอง", latitude: 18.5877, longitude: 98.4867, elevation: 2565, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "06:00 - 18:00", tags: ["เดินป่า", "ชมวิว", "ดูนก", "ชมน้ำตก", "ถ่ายภาพ"] },
  { name: "อุทยานแห่งชาติดอยสุเทพ-ปุย", nameEn: "Doi Suthep-Pui National Park", description: "อุทยานแห่งชาติดอยสุเทพ-ปุย ตั้งอยู่ทางตะวันตกของเมืองเชียงใหม่ เป็นที่ตั้งของวัดพระธาตุดอยสุเทพ มีเส้นทางเดินศึกษาธรรมชาติ น้ำตกห้วยแก้ว และจุดชมวิวเมืองเชียงใหม่", province: "เชียงใหม่", district: "เมืองเชียงใหม่", latitude: 18.8047, longitude: 98.9219, elevation: 1676, entryFeeThai: 50, entryFeeForeigner: 200, openingHours: "06:00 - 18:00", tags: ["ชมวิว", "ถ่ายภาพ", "เดินป่า"] },
  { name: "อุทยานแห่งชาติดอยผ้าห่มปก", nameEn: "Doi Pha Hom Pok National Park", description: "อุทยานแห่งชาติดอยผ้าห่มปก เป็นที่ตั้งของยอดดอยผ้าห่มปก สูงเป็นอันดับ 2 ของไทย (2,285 เมตร) มีบ่อน้ำร้อนฝาง น้ำตกหลายแห่ง และป่าดิบเขาที่สมบูรณ์", province: "เชียงใหม่", district: "ฝาง", latitude: 20.0286, longitude: 99.1553, elevation: 2285, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["เดินป่า", "บ่อน้ำร้อน", "ชมน้ำตก", "ชมวิว"] },
  { name: "อุทยานแห่งชาติห้วยน้ำดัง", nameEn: "Huai Nam Dang National Park", description: "อุทยานแห่งชาติห้วยน้ำดัง เป็นจุดชมทะเลหมอกที่สวยที่สุดแห่งหนึ่งในภาคเหนือ มีลานกางเต็นท์และจุดชมวิวดอยกิ่วลม ครอบคลุมพื้นที่เชียงใหม่-แม่ฮ่องสอน", province: "เชียงใหม่", district: "แม่แตง", latitude: 19.3100, longitude: 98.6050, elevation: 1543, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "06:00 - 18:00", tags: ["แคมป์ปิ้ง", "ชมวิว", "ถ่ายภาพ", "ดูดาว"] },
  { name: "อุทยานแห่งชาติศรีลานนา", nameEn: "Sri Lanna National Park", description: "อุทยานแห่งชาติศรีลานนา ครอบคลุมพื้นที่อ่างเก็บน้ำเขื่อนแม่กวง เหมาะสำหรับกิจกรรมทางน้ำ ล่องแก่ง และชมทิวทัศน์ทะเลสาบกลางหุบเขา", province: "เชียงใหม่", district: "แม่แตง", latitude: 19.0972, longitude: 99.0833, elevation: 500, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ล่องแก่ง", "ชมวิว", "ปั่นจักรยาน"] },
  { name: "อุทยานแห่งชาติขุนขาน", nameEn: "Khun Khan National Park", description: "อุทยานแห่งชาติขุนขาน ตั้งอยู่ในอำเภอสันป่าตอง จังหวัดเชียงใหม่ มีน้ำตกและเส้นทางเดินป่าผ่านป่าดิบเขา เป็นแหล่งต้นน้ำลำธารที่สำคัญ", province: "เชียงใหม่", district: "สันป่าตอง", latitude: 18.4500, longitude: 98.5333, elevation: 1200, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["เดินป่า", "ชมน้ำตก"] },
  { name: "อุทยานแห่งชาติแม่วาง", nameEn: "Mae Wang National Park", description: "อุทยานแห่งชาติแม่วาง จังหวัดเชียงใหม่ มีเส้นทางเดินป่าสู่น้ำตกและลำธาร บรรยากาศเงียบสงบ เหมาะสำหรับพักผ่อนหย่อนใจกลางธรรมชาติ", province: "เชียงใหม่", district: "แม่วาง", latitude: 18.5167, longitude: 98.6333, elevation: 900, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["เดินป่า", "ชมน้ำตก", "แคมป์ปิ้ง"] },
  { name: "อุทยานแห่งชาติแม่ตะไคร้", nameEn: "Mae Takhrai National Park", description: "อุทยานแห่งชาติแม่ตะไคร้ ครอบคลุมพื้นที่เชียงใหม่-เชียงราย มีป่าดิบเขาที่สมบูรณ์ น้ำตก และเส้นทางเดินป่าศึกษาธรรมชาติ", province: "เชียงใหม่", district: "ดอยสะเก็ด", latitude: 19.0500, longitude: 99.3333, elevation: 900, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["เดินป่า", "ชมน้ำตก", "ดูนก"] },

  // === เชียงราย ===
  { name: "อุทยานแห่งชาติขุนแจ", nameEn: "Khun Chae National Park", description: "อุทยานแห่งชาติขุนแจ จังหวัดเชียงราย มีจุดชมวิวทะเลหมอกกิ่วฝิ่น น้ำตก และป่าดิบเขาที่สมบูรณ์ เป็นแหล่งต้นน้ำแม่ลาว", province: "เชียงราย", district: "เวียงป่าเป้า", latitude: 19.2000, longitude: 99.4500, elevation: 1550, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ชมวิว", "เดินป่า", "ถ่ายภาพ"] },
  { name: "อุทยานแห่งชาติดอยหลวง", nameEn: "Doi Luang National Park", description: "อุทยานแห่งชาติดอยหลวง ครอบคลุมพื้นที่ 3 จังหวัด เชียงราย พะเยา ลำปาง มีน้ำตกปูแกง (วังบัวบาน) น้ำตกจำปาทอง และป่าดิบเขาที่สมบูรณ์", province: "เชียงราย", district: "พาน", latitude: 19.1667, longitude: 99.6167, elevation: 1694, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ชมน้ำตก", "เดินป่า", "แคมป์ปิ้ง"] },

  // === ลำปาง / ลำพูน ===
  { name: "อุทยานแห่งชาติแจ้ซ้อน", nameEn: "Chae Son National Park", description: "อุทยานแห่งชาติแจ้ซ้อน มีชื่อเสียงเรื่องบ่อน้ำร้อนธรรมชาติที่สามารถต้มไข่ได้ น้ำตกแจ้ซ้อน และลานกางเต็นท์ท่ามกลางธรรมชาติ จังหวัดลำปาง", province: "ลำปาง", district: "เมืองปาน", latitude: 18.8353, longitude: 99.4097, elevation: 750, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["บ่อน้ำร้อน", "ชมน้ำตก", "แคมป์ปิ้ง"] },
  { name: "อุทยานแห่งชาติดอยจง", nameEn: "Doi Jong National Park", description: "อุทยานแห่งชาติดอยจง ครอบคลุมพื้นที่ลำปาง-ลำพูน มีทิวทัศน์ทิวเขาสลับซับซ้อน ป่าเบญจพรรณ และเส้นทางเดินป่าที่เงียบสงบ", province: "ลำปาง", district: "แม่ทะ", latitude: 18.2000, longitude: 99.3500, elevation: 1100, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["เดินป่า", "ชมวิว"] },
  { name: "อุทยานแห่งชาติถ้ำผาไท", nameEn: "Tham Pha Thai National Park", description: "อุทยานแห่งชาติถ้ำผาไท จังหวัดลำปาง มีถ้ำหินปูนขนาดใหญ่ หินงอก หินย้อยสวยงาม และป่าเบญจพรรณโดยรอบ เหมาะสำหรับสำรวจถ้ำ", province: "ลำปาง", district: "เมืองลำปาง", latitude: 18.4167, longitude: 99.6167, elevation: 400, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["สำรวจถ้ำ", "ถ่ายภาพ", "ธรณีวิทยา"] },
  { name: "อุทยานแห่งชาติดอยขุนตาล", nameEn: "Doi Khun Tan National Park", description: "อุทยานแห่งชาติดอยขุนตาล ครอบคลุมพื้นที่ลำปาง-ลำพูน สามารถเดินทางโดยรถไฟผ่านอุโมงค์ขุนตาล มีเส้นทางเดินป่าขึ้นยอดดอยชมวิวทะเลหมอก", province: "ลำปาง", district: "แม่ทา", latitude: 18.3833, longitude: 99.0667, elevation: 1373, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["เดินป่า", "ชมวิว", "แคมป์ปิ้ง", "ถ่ายภาพ"] },
  { name: "อุทยานแห่งชาติแม่ปิง", nameEn: "Mae Ping National Park", description: "อุทยานแห่งชาติแม่ปิง ครอบคลุมพื้นที่ลำพูน ตาก เชียงใหม่ มีเขื่อนภูมิพล ล่องเรือชมผาหินริมแม่น้ำปิง ถ้ำ และน้ำตกก้อหลวง", province: "ลำพูน", district: "ลี้", latitude: 17.8333, longitude: 98.8500, elevation: 600, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ล่องเรือ", "ชมวิว", "สำรวจถ้ำ", "ชมน้ำตก"] },

  // === แพร่ ===
  { name: "อุทยานแห่งชาติแม่ยม", nameEn: "Mae Yom National Park", description: "อุทยานแห่งชาติแม่ยม ครอบคลุมพื้นที่แพร่-ลำปาง มีป่าสักธรรมชาติผืนใหญ่ที่สุดในโลก แก่งเสือเต้น และทิวทัศน์ที่สวยงามริมแม่น้ำยม", province: "แพร่", district: "สอง", latitude: 18.2500, longitude: 99.7500, elevation: 800, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["เดินป่า", "ล่องแก่ง", "ชมวิว"] },
  { name: "อุทยานแห่งชาติเวียงโกศัย", nameEn: "Wiang Kosai National Park", description: "อุทยานแห่งชาติเวียงโกศัย จังหวัดแพร่ มีน้ำตกแม่แคม ถ้ำผาแดง และป่าสนเขตร้อนที่สวยงาม เป็นแหล่งต้นน้ำลำธารสำคัญ", province: "แพร่", district: "วังชิ้น", latitude: 18.0000, longitude: 99.4667, elevation: 900, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ชมน้ำตก", "สำรวจถ้ำ", "เดินป่า"] },
  { name: "อุทยานแห่งชาติดอยผากลอง", nameEn: "Doi Pha Klong National Park", description: "อุทยานแห่งชาติดอยผากลอง จังหวัดแพร่ มีทุ่งดอกบัวตอง จุดชมวิวทะเลหมอก และป่าเบญจพรรณที่สมบูรณ์ เป็นอุทยานขนาดเล็กที่เงียบสงบ", province: "แพร่", district: "ลอง", latitude: 18.1167, longitude: 99.8167, elevation: 1100, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ชมวิว", "ถ่ายภาพ", "เดินป่า"] },

  // === น่าน ===
  { name: "อุทยานแห่งชาติดอยภูคา", nameEn: "Doi Phu Kha National Park", description: "อุทยานแห่งชาติดอยภูคา จังหวัดน่าน เป็นผืนป่าที่มีความหลากหลายทางชีวภาพสูง เป็นที่อยู่ของต้นชมพูภูคาซึ่งเป็นพันธุ์ไม้หายาก มีเส้นทางเดินป่าและจุดชมวิวสวยงาม", province: "น่าน", district: "ปัว", latitude: 19.1944, longitude: 101.0750, elevation: 1980, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["เดินป่า", "ชมวิว", "ดูนก", "ถ่ายภาพ"] },
  { name: "อุทยานแห่งชาติขุนน่าน", nameEn: "Khun Nan National Park", description: "อุทยานแห่งชาติขุนน่าน ตั้งอยู่ในป่าต้นน้ำน่าน มีเส้นทางเดินป่าที่ท้าทาย น้ำตกสวยงาม และทะเลหมอกยามเช้า เป็นอุทยานที่ยังคงความบริสุทธิ์ดั้งเดิม", province: "น่าน", district: "บ่อเกลือ", latitude: 19.3833, longitude: 101.1833, elevation: 1600, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["เดินป่า", "ชมวิว", "ชมน้ำตก"] },
  { name: "อุทยานแห่งชาติแม่จริม", nameEn: "Mae Charim National Park", description: "อุทยานแห่งชาติแม่จริม จังหวัดน่าน มีน้ำตกศิลาเพชรสวยงาม ลำน้ำว้าที่เหมาะสำหรับล่องแก่ง และป่าเบญจพรรณที่อุดมสมบูรณ์", province: "น่าน", district: "แม่จริม", latitude: 18.8000, longitude: 100.8833, elevation: 500, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ล่องแก่ง", "ชมน้ำตก", "เดินป่า"] },
  { name: "อุทยานแห่งชาตินันทบุรี", nameEn: "Nanthaburi National Park", description: "อุทยานแห่งชาตินันทบุรี จังหวัดน่าน เป็นที่ตั้งของเขื่อนสิริกิติ์ มีอ่างเก็บน้ำขนาดใหญ่ เส้นทางเดินป่า และทิวทัศน์เขื่อนกลางหุบเขาที่สวยงาม", province: "น่าน", district: "เมืองน่าน", latitude: 18.7000, longitude: 100.8500, elevation: 400, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ชมวิว", "ล่องเรือ", "เดินป่า"] },
  { name: "อุทยานแห่งชาติศรีน่าน", nameEn: "Sri Nan National Park", description: "อุทยานแห่งชาติศรีน่าน จังหวัดน่าน มีเสาดินนาน้อย ปรากฏการณ์ทางธรณีวิทยาที่สวยงาม ป่าเต็งรังและป่าเบญจพรรณ เหมาะสำหรับศึกษาธรรมชาติ", province: "น่าน", district: "นาน้อย", latitude: 18.3667, longitude: 100.8333, elevation: 500, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ธรณีวิทยา", "ถ่ายภาพ", "เดินป่า"] },

  // === พะเยา / แม่ฮ่องสอน ===
  { name: "อุทยานแห่งชาติดอยภูนาง", nameEn: "Doi Phu Nang National Park", description: "อุทยานแห่งชาติดอยภูนาง จังหวัดพะเยา มีทุ่งดอกบัวตองขนาดใหญ่ในช่วงเดือนพฤศจิกายน จุดชมวิวทะเลหมอก และเส้นทางเดินป่าผ่านป่าเบญจพรรณ", province: "พะเยา", district: "ปง", latitude: 19.0167, longitude: 100.4833, elevation: 1100, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ชมวิว", "ถ่ายภาพ", "เดินป่า"] },
  { name: "อุทยานแห่งชาติน้ำตกแม่สุรินทร์", nameEn: "Namtok Mae Surin National Park", description: "อุทยานแห่งชาติน้ำตกแม่สุรินทร์ จังหวัดแม่ฮ่องสอน เป็นที่ตั้งของน้ำตกแม่สุรินทร์ น้ำตกชั้นเดียวที่สูงที่สุดในประเทศไทย (100 เมตร) ท่ามกลางป่าดิบเขา", province: "แม่ฮ่องสอน", district: "เมืองแม่ฮ่องสอน", latitude: 19.3167, longitude: 97.9167, elevation: 800, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ชมน้ำตก", "เดินป่า", "ถ่ายภาพ"] },
  { name: "อุทยานแห่งชาติสาละวิน", nameEn: "Salawin National Park", description: "อุทยานแห่งชาติสาละวิน จังหวัดแม่ฮ่องสอน ตั้งอยู่ริมแม่น้ำสาละวินชายแดนไทย-เมียนมา มีทิวทัศน์ริมน้ำที่สวยงาม ป่าดิบแล้ง และวิถีชีวิตชาวเขา", province: "แม่ฮ่องสอน", district: "แม่สะเรียง", latitude: 18.0333, longitude: 97.7167, elevation: 400, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ล่องเรือ", "ชมวิว", "ถ่ายภาพ"] },

  // === อุตรดิตถ์ / สุโขทัย ===
  { name: "อุทยานแห่งชาติต้นสักใหญ่", nameEn: "Ton Sak Yai National Park", description: "อุทยานแห่งชาติต้นสักใหญ่ จังหวัดอุตรดิตถ์ เป็นที่ตั้งของต้นสักทองที่ใหญ่ที่สุดในโลก มีป่าสักธรรมชาติที่สมบูรณ์ น้ำตก และเส้นทางเดินป่า", province: "อุตรดิตถ์", district: "น้ำปาด", latitude: 17.9667, longitude: 100.5833, elevation: 600, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["เดินป่า", "ชมน้ำตก", "ถ่ายภาพ"] },
  { name: "อุทยานแห่งชาติลำน้ำน่าน", nameEn: "Lam Nam Nan National Park", description: "อุทยานแห่งชาติลำน้ำน่าน ครอบคลุมพื้นที่อุตรดิตถ์-แพร่ มีเขื่อนสิริกิติ์ ป่าดิบเขาสมบูรณ์ ล่องเรือชมวิวทิวทัศน์ริมเขื่อน", province: "อุตรดิตถ์", district: "ท่าปลา", latitude: 17.8333, longitude: 100.5000, elevation: 500, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ล่องเรือ", "ชมวิว", "เดินป่า"] },
  { name: "อุทยานแห่งชาติภูสอยดาว", nameEn: "Phu Soi Dao National Park", description: "อุทยานแห่งชาติภูสอยดาว ครอบคลุมพื้นที่อุตรดิตถ์-พิษณุโลก ขึ้นชื่อเรื่องทุ่งดอกหงส์เหิรบนยอดเขา ทะเลหมอกสวยงาม และลานหินปุ่มที่หาดูยาก", province: "อุตรดิตถ์", district: "บ้านโคก", latitude: 17.5500, longitude: 100.6500, elevation: 2102, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["เดินป่า", "ชมวิว", "แคมป์ปิ้ง", "ถ่ายภาพ"] },
  { name: "อุทยานแห่งชาติรามคำแหง", nameEn: "Ramkhamhaeng National Park", description: "อุทยานแห่งชาติรามคำแหง (เขาหลวง) จังหวัดสุโขทัย มียอดเขาหลวงสูง 1,200 เมตร จุดชมวิวทะเลหมอก และพระบรมธาตุบนยอดเขา", province: "สุโขทัย", district: "คีรีมาศ", latitude: 16.9833, longitude: 99.6333, elevation: 1200, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["เดินป่า", "ชมวิว", "แคมป์ปิ้ง"] },
  { name: "อุทยานแห่งชาติศรีสัชนาลัย", nameEn: "Si Satchanalai National Park", description: "อุทยานแห่งชาติศรีสัชนาลัย จังหวัดสุโขทัย มีน้ำตกหลายแห่ง ป่าดิบแล้ง และอยู่ใกล้อุทยานประวัติศาสตร์ศรีสัชนาลัย เหมาะท่องเที่ยวเชิงธรรมชาติควบคู่ประวัติศาสตร์", province: "สุโขทัย", district: "ศรีสัชนาลัย", latitude: 17.4500, longitude: 99.8500, elevation: 800, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ชมน้ำตก", "เดินป่า", "ประวัติศาสตร์"] },

  // === พิษณุโลก / เพชรบูรณ์ ===
  { name: "อุทยานแห่งชาติภูหินร่องกล้า", nameEn: "Phu Hin Rong Kla National Park", description: "อุทยานแห่งชาติภูหินร่องกล้า ครอบคลุมพื้นที่พิษณุโลก-เลย มีลานหินแตก ทุ่งดอกไม้ หมอกยามเช้า และเป็นสถานที่ทางประวัติศาสตร์สำคัญ", province: "พิษณุโลก", district: "นครไทย", latitude: 16.9833, longitude: 100.9833, elevation: 1760, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ชมวิว", "ถ่ายภาพ", "ประวัติศาสตร์", "แคมป์ปิ้ง"] },
  { name: "อุทยานแห่งชาติทุ่งแสลงหลวง", nameEn: "Thung Salaeng Luang National Park", description: "อุทยานแห่งชาติทุ่งแสลงหลวง ครอบคลุมพื้นที่พิษณุโลก-เพชรบูรณ์ เป็นทุ่งหญ้าสะวันนาที่ใหญ่ที่สุดในไทย มีน้ำตกแก่งโสภา และทะเลหมอกสวยงาม", province: "พิษณุโลก", district: "วังทอง", latitude: 16.7333, longitude: 100.8333, elevation: 1028, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ชมวิว", "ถ่ายภาพ", "แคมป์ปิ้ง", "เดินป่า"] },
  { name: "อุทยานแห่งชาติน้ำตกชาติตระการ", nameEn: "Namtok Chat Trakan National Park", description: "อุทยานแห่งชาติน้ำตกชาติตระการ จังหวัดพิษณุโลก มีน้ำตกชาติตระการที่ไหลลดหลั่นหลายชั้น ป่าดิบชื้นสมบูรณ์ และเส้นทางเดินป่าศึกษาธรรมชาติ", province: "พิษณุโลก", district: "ชาติตระการ", latitude: 17.1833, longitude: 100.8500, elevation: 600, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ชมน้ำตก", "เดินป่า"] },
  { name: "อุทยานแห่งชาติน้ำหนาว", nameEn: "Nam Nao National Park", description: "อุทยานแห่งชาติน้ำหนาว จังหวัดเพชรบูรณ์ เป็นป่าดิบเขาที่สมบูรณ์ที่สุดแห่งหนึ่ง อากาศเย็นตลอดปี มีสัตว์ป่าหลากหลาย ทุ่งหญ้า และน้ำตกสวยงาม", province: "เพชรบูรณ์", district: "น้ำหนาว", latitude: 16.7333, longitude: 101.5667, elevation: 860, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["เดินป่า", "ดูสัตว์ป่า", "ดูนก", "แคมป์ปิ้ง"] },
  { name: "อุทยานแห่งชาติตาดหมอก", nameEn: "Tat Mok National Park", description: "อุทยานแห่งชาติตาดหมอก จังหวัดเพชรบูรณ์ มีน้ำตกตาดหมอก น้ำตกสายรุ้ง จุดชมวิวทะเลหมอกบนยอดเขาค้อ ป่าสนสามใบ บรรยากาศเย็นสบาย", province: "เพชรบูรณ์", district: "เขาค้อ", latitude: 16.6167, longitude: 101.0000, elevation: 1100, entryFeeThai: 100, entryFeeForeigner: 300, openingHours: "08:00 - 16:30", tags: ["ชมน้ำตก", "ชมวิว", "ถ่ายภาพ", "แคมป์ปิ้ง"] },
];
